import {
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const listings = pgTable(
  "listings",
  {
    id: serial("id").primaryKey(),
    external_id: text("external_id").unique().notNull(),
    source: text("source").notNull(),
    property_type: text("property_type").notNull(),
    transaction_type: text("transaction_type").notNull(),
    title: text("title"),
    description: text("description"),
    price: doublePrecision("price"),
    currency: text("currency").default("CZK"),
    price_note: text("price_note"),
    address: text("address"),
    city: text("city"),
    district: text("district"),
    region: text("region"),
    latitude: doublePrecision("latitude"),
    longitude: doublePrecision("longitude"),
    size_m2: doublePrecision("size_m2"),
    layout: text("layout"),
    floor: integer("floor"),
    total_floors: integer("total_floors"),
    condition: text("condition"),
    construction: text("construction"),
    ownership: text("ownership"),
    furnishing: text("furnishing"),
    energy_rating: text("energy_rating"),
    amenities: text("amenities"),
    image_urls: jsonb("image_urls").$type<string[]>().default([]),
    thumbnail_url: text("thumbnail_url"),
    source_url: text("source_url"),
    listed_at: timestamp("listed_at", { mode: "string" }),
    scraped_at: timestamp("scraped_at", { mode: "string" }).defaultNow(),
    created_at: timestamp("created_at", { mode: "string" }).defaultNow(),
    is_active: boolean("is_active").default(true),
    deactivated_at: timestamp("deactivated_at", { mode: "string" }),
    seller_name: text("seller_name"),
    seller_phone: text("seller_phone"),
    seller_email: text("seller_email"),
    seller_company: text("seller_company"),
    additional_params: jsonb("additional_params").$type<Record<string, unknown>>(),
  },
  (table) => [
    index("idx_listings_city").on(table.city),
    index("idx_listings_price").on(table.price),
    index("idx_listings_source").on(table.source),
    index("idx_listings_property_type").on(table.property_type),
    index("idx_listings_transaction_type").on(table.transaction_type),
    index("idx_listings_is_active").on(table.is_active),
    index("idx_listings_external_id").on(table.external_id),
    index("idx_listings_geo").on(table.is_active, table.latitude, table.longitude),
    index("idx_listings_active_listed").on(table.is_active, table.listed_at),
  ],
);

export type ListingRow = typeof listings.$inferSelect;
export type NewListing = typeof listings.$inferInsert;
